### PR TITLE
chore(event_kind): Board variant module + 8 call-site migrations (#8455 Phase 2)

### PR DESCRIPTION
**Pull request by jeong-sik**
## Summary

Phase 2 of #8455. Extends the event-kind SSOT introduced in #8635 with the `board.*` family (Posted, Commented, Voted, Deleted). Same pattern as Task.

## New variant module

`Event_kind.Board.t` — 4 variants enumerating every `board.*` event emitted in `lib/`. `to_string` / `of_string` round-trip, `all` enumerates. Parse boundary is `of_string` at ingress; internal code uses variants so typos become compile errors.

## Migrated emitters (8 sites)

| File | Sites |
|------|-------|
| `lib/tool_inline_dispatch_extra.ml` | 4 `~kind:` + 4 `~tags:` entries |
| `lib/server/server_bootstrap_loops.ml` | 4 tuple-builder sites (posted / commented / voted×2) |

Verification: `Event_kind.Board.Potsed` → `Error: Unbound constructor Potsed. Did you mean Posted?`.

## Test

`test/test_event_kind.ml` — adds round-trip / typo-rejection / prefix-invariant triple for Board, mirroring Task.

## Not in this PR

`agent.*`, `keeper.*`, `decision.*`, `operation.*`, `message.*`, `policy.*`, `tool.*` families land in follow-ups. #8455 stays open as umbrella.

## Test plan

- [ ] CI green (test_event_kind now exercises both Task and Board)
- No behavior change; pure SSOT extension.

### CODE REVIEW

**Comment by jeong-sik** [comment]
Tick 30 rebase attempted — pushed to origin but branch DIRTY again (main moved further post-push). Likely same structural conflict class as #8639. Autocoder cycle faster than human broker — recommend autocoder to re-generate with current main.
