### PR TITLE
fix(build): restore main build broken by #21714 and #21721

### PR DESCRIPTION
**Pull request by jeong-sik**
## 목표

main 빌드 RED 복구. 최근 머지 후 CI `Build and Test`/`Lint`가 fast-fail하면서 뒤의 compile break가 가려졌습니다. 적대적으로 끝까지 추적하면 현재 main에는 세 가지 compile-shape 문제가 있습니다.

## Break 1 — `lib/gate_keeper_backend.ml`

`dispatch_core`가 leading `?on_text_snapshot` 옵셔널을 받고 마지막 인자가 labeled `~content`로 끝나서 optional이 erase될 수 없습니다. 그 결과 `dispatch`의 inferred type에 `?on_text_snapshot`이 새어 `.mli`의 `dispatch` 선언과 불일치합니다.

수정: `dispatch_core`에 trailing `()` positional을 추가하고 내부 호출처 2곳에서 `()`를 전달합니다. `.mli` 무변경, 런타임 동작 변화 없음.

## Break 2 — `lib/server/server_discord_in_process_gateway.ml`

`Stream_failed` 분기 split 이후 `with_response_wait_typing_indicator` outer match를 닫는 `)`가 하나 빠져 `let on_event`에서 `Syntax error: ) expected`가 납니다.

수정: `Stream_overflow_send_failed` tail에서 누락된 outer match paren을 복원합니다.

## Break 3 — `test/test_keeper_memory_os.ml`

`module Reconcile = Masc.Keeper_memory_os_reconcile`가 top-level에 두 번 선언되어 `test_rfc0259_reconcile` target build에서 `Multiple definition of the module name Reconcile`로 실패합니다.

수정: 중복 alias 한 줄을 제거합니다.

## 검증

- `opam exec -- ocamlformat --check lib/gate_keeper_backend.ml lib/server/server_discord_in_process_gateway.ml test/test_keeper_memory_os.ml`
- `git diff --check origin/main...HEAD`
- `rg "module Reconcile" test/test_keeper_memory_os.ml` → single occurrence

Full Dune/build는 owner 지시에 따라 로컬에서는 돌리지 않았습니다. CI `Build and Test`가 이 PR의 authoritative gate입니다.

## 경계 / RFC

순수 compile-shape 복구입니다. 공개 `.mli` 변경, telemetry/counter, cap/cooldown, 문자열 classifier, runtime behavior 변경 없음. RFC 불필요.

Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>

### CODE REVIEW

**Comment by jeong-sik** [comment]
Adversarial follow-up pushed at 507302c7b8. The previous two-file build repair still left the next hidden compile blocker: test/test_keeper_memory_os.ml defined module Reconcile twice, which fails the rfc0259 reconcile test target with Multiple definition of the module name Reconcile. I rebased onto latest origin/main, removed the duplicate alias, and updated the PR body so it no longer overclaims local full-build validation. Local checks: ocamlformat --check on the three changed OCaml files, git diff --check origin/main...HEAD, and rg confirms only one Reconcile alias remains. Full Dune/build remains deferred per owner instruction; CI Build and Test is the authoritative gate.

**Review by anyang-keepers — APPROVED** [review]
## Review: APPROVED

I read the full diff. Three changes, all correct:

### 1. `lib/gate_keeper_backend.ml` — trailing `()` on `dispatch_core`

**Correct.** The `?on_text_snapshot` optional parameter leaks into `dispatch`'s inferred type when omitted, breaking the `.mli` signature. Adding a trailing `()` unit parameter makes the optional erasable (warning 16 fix). Both callers (`dispatch`, `dispatch_with_text_snapshot`) pass `()` correctly. The comment explains the rationale clearly.

### 2. `lib/server/server_discord_in_process_gateway.ml` — parenthesis fix

**Correct.** The original had `Discord_observability.record_reply Discord_observability.Reply_send_failed)` — one closing paren for `record_reply`. The fix adds the second `)` to close the `record_inbound_dispatch` call. This is a syntax fix that would have been a compile error.

### 3. `test/test_keeper_memory_os.ml` — duplicate `module Reconcile` removed

**Correct.** `module Reconcile = Masc.Keeper_memory_os_reconcile` appeared twice. Removing the duplicate fixes the `Multiple definition of the module name Reconcile` error.

**Verdict**: No BLOCKs. All changes are minimal, correct, and well-explained. CI is all green. Ready to merge.
