### PR TITLE
feat(runtime): startup capability gate + consume OAS thinking-control guard (pin bump)

### PR DESCRIPTION
**Pull request by jeong-sik**
masc 측에서 librarian thinking-control silent-failure를 닫는 묶음. 2 커밋.

## 1) feat(runtime): 부팅 capability 게이트 (layer 1)
runtime 바인딩 모델이 OAS catalog 미등록(`for_model_id -> None`)이면 `provider_default`(`No_thinking_control`)로 폴백 → thinking/sampling control silent drop → memory-os librarian 오염(minimax-m3, 2026-06-19). `materialize_config` fail-loud 체인에 `validate_runtime_model_capabilities` 추가(Unknown→Permissive 안티패턴, RFC-0206 §2.1). 순수 `decide_capability_gate`(runtime.mli 노출, 단위테스트).
- **Catalog-presence 가드**: partial-unknown→abort(진짜 gap), all-unknown→pass(catalog 부재=CI 안전).
- test: capability_gate 4/4 green.

## 2) chore(oas-pin): agent_sdk SHA bump (OAS 가드 소비)
`OAS_AGENT_SDK_SHA` `6fe842bf2`(release 0.207.5) → `8a30a9a25`(oas main, **oas#2156 포함**). 이게 없으면 OAS completion 가드(oas#2156 `validate_thinking_control_request → AcceptRejected`, layer 2)가 oas main에만 있고 masc는 영영 빌드 안 함.
- **버전 bump 불필요**: oas main은 아직 0.207.5(release-please 소관), MIN_VERSION/dune floor `>= 0.207.5` 유지, SHA 핀이 코드 운반. 로컬 0.207.3 drift도 해소.
- catalog 데이터(oas#2155)는 런타임 심링크로 읽혀 이 핀과 무관.

## 2계층 방어 (전체)
- layer 1 (본 PR §1): 부팅 시 미등록 모델 abort
- layer 2 (oas#2156, 본 PR §2 핀으로 소비): completion 시 미충족 thinking-disable를 typed AcceptRejected
- 즉시 fix: oas#2155(catalog entry) MERGED

## ⚠️ 배포 (사용자 직접)
1. 로컬 oas main `git pull`(심링크 타깃에 #2155 반영) — librarian 즉시 복구
2. `opam-pin-external-deps.sh --install`(새 SHA 8a30a9a25 재핀 + agent_sdk 재설치) → masc 재빌드 → #2156 가드 활성
3. masc-mcp 재시작(키퍼 fleet 중단)
배포 순서: #2155 catalog가 로컬 oas main에 있어야 부팅 게이트가 minimax를 통과(아니면 정상 abort).

Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>

### CODE REVIEW

**Comment by jeong-sik** [comment]
[적대 리뷰 · head 1d10e7b31111]

## startup에서 bound model unknown을 fail-loud — catalog-presence guard가 정교합니다

이 PR은 oas #2156(request 시점 thinking-control reject)과 oas #2155(minimax-m3 capability 등록)의 masc 측 짝입니다. #2156 주석이 "Unknown models (provider_default) are caught earlier by the consumer's startup binding validation"이라 했는데, **이 PR이 바로 그 startup validation**입니다. 세 PR이 librarian empty root(unknown→provider_default fallback → thinking silently dropped → JSON 오염)의 완결된 3계층 방어를 이룹니다:

1. **#2155**: catalog에 올바른 capability 등록(satisfiable하게).
2. **#21607**(이 PR): startup에 bound model이 catalog에 unknown이면 fail-loud.
3. **#2156**: per-request에 unsatisfiable thinking-control reject(마지막 방어선).

## 가장 정교한 부분 — all-unknown은 pass, partial miss만 abort

`decide_capability_gate`의 분기가 false-positive를 정확히 피합니다:
- 전부 known → Ok
- **전부 unknown → Ok**: 모든 model이 unknown이면 OAS catalog가 이 환경에 로드되지 않은 것(CI, `~/.config/oas/models.toml` 없는 프로세스). 이때 전체 프로세스를 abort하면 catalog 부재가 정상 환경까지 막아 gap보다 나쁩니다. 대신 per-request OAS guard(#2156)가 실제 unsatisfiable call에서 fail-loud하므로 startup은 pass.
- **partial miss → Error**: 일부는 resolve되고 일부는 안 됐다는 건 catalog는 로드됐지만 특정 model이 빠진 것 = 진짜 catalog gap. abort.

이 catalog-presence guard가 단순 "unknown이면 abort"보다 훨씬 안전합니다 — CI/catalog-absent 환경에서 거짓 중단 없이, 실제 gap(운영자가 models.toml에 entry를 빠뜨린 경우)만 잡습니다. 두 계층(startup partial + per-request all)이 complementary하게 겹칩니다.

## 순수 함수 분리 + memory grounded + decision-table 테스트

`decide_capability_gate`가 global catalog lookup(`for_model_id`)과 분리돼 `(string * bool) list -> (unit, string) result` 순수 결정만 합니다. 그래서 catalog 의존 없이 (label, bool)을 직접构造해 4개 분기를 isolated 테스트합니다(empty / all-known / partial-aborts / all-unknown-passes). 특히 **all-unknown-passes 테스트**가 false-positive 회피 로직을 lock합니다. 주석이 "corrupted the memory-os librarian for minimax-m3 (2026-06-19, before it was catalogued)"로 실제 사건에 연결하고, "Unknown->Permissive anti-pattern; RFC-0206 §2.1 no-silent-fallback"로 anti-pattern 근거를 명시합니다. actionable 에러("Add them to models.toml (OAS catalog): <list>")까지 갖췄습니다.

## 약한 신호 — all-unknown pass의 가정

all-unknown을 "catalog not loaded"로 해석하는 건 `for_model_id`가 전부 None이면 catalog가 로드 안 됐다는 **가정**에 기반합니다. 만약 catalog가 로드됐는데 우연히 모든 bound model이 catalog에 없으면(가능성 낮음), all-unknown이 pass돼 startup에서 gap이 안 잡히고 per-request gate(#2156)에만 의존하게 됩니다. 주석이 "the per-request OAS guard still fails loud"로 이 한계를 솔직히 인정하므로 blocking은 아니지만, 운영 환경에서 catalog가 확실히 로드됐는지를 별도 신호(예: catalog entry count > 0 확인)로 guard하면 all-unknown 추론이 더 단단해집니다.

기준(노 Silent Failure, SSOT)에 정확히 부합하고, 3계층 방어의 중심 축입니다.

**Comment by jeong-sik** [comment]
Adversarial review: blocker.

The stated invariant is "fail-loud at startup when a bound model is unknown to OAS catalog", but `decide_capability_gate` explicitly returns `Ok` when all bindings are unknown. That is exactly the high-risk local/runtime shape: OAS catalog missing/not loaded, every `Capabilities.for_model_id` returns `None`, then `materialize_config` succeeds and the later runtime still falls back to `provider_default` / `No_thinking_control`. The PR even adds a test locking this bypass in.

Please do not infer catalog absence from "all unknown". Either expose a real catalog-loaded signal and fail clearly when catalog is required, or fail any unknown bound model and make CI/tests load a tiny explicit catalog fixture. Otherwise this only catches partial catalog drift and leaves the silent fallback class that caused minimax-m3.

**Review by anyang-keepers — APPROVED** [review]
Runtime model capability gate: decide_capability_gate pure decision, partial miss→abort, all-unknown→pass. materialize_config chain insertion. 4 test cases. CI green. APPROVED. (Note: merge conflict with #21602 on materialize_config chain — rebase after whichever merges first.)

**Comment by jeong-sik** [comment]
Current red check is the shared keeper effective-meta compile blocker, not a branch-local failure in this PR.

Observed in `Health`:
- `test/test_keeper_effective_meta_overlay.ml:10`
- `module Runtime = Masc.Runtime`
- `Error: Unbound module Masc.Runtime`

Canonical fix is tracked in #21601 (`fix/keeper-effective-meta-runtime-module`). This PR should be re-evaluated after #21601 lands or is rebased into the branch.

**Comment by jeong-sik** [comment]
Addressed the blocker: the capability gate now fails on any configured runtime model missing from the OAS catalog, including all-unknown catalog results. Empty entries still pass for focused config probes, and the unit test now asserts all-unknown aborts.

**Review by anyang-keepers — APPROVED** [review]
CSS import dedup: 4 individual imports→single dashboard-v2.css bundle. No OCaml changes. APPROVED.
