### PR TITLE
hotfix(keeper-turn-driver): drop incorrect Agent_sdk.Error prefix on Timeout — main HEAD broken since #19145

### PR DESCRIPTION
**Pull request by jeong-sik**
## ⚠️ HOTFIX — main HEAD broken since PR #19145

origin/main `b67f6d82a` 의 `lib/keeper/keeper_turn_driver_try_cascade.ml:604` 가 `dune build lib/` fail:

```
File "lib/keeper/keeper_turn_driver_try_cascade.ml", line 604, characters 18-41:
604 |                  (Agent_sdk.Error.Timeout
                        ^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound constructor Agent_sdk.Error.Timeout
```

PR #19145 (RFC-0197 per-candidate watchdog) 머지 후 *9 PR 동안 silent*:
- #19146, #19147, #19148, #19149, #19150, #19151, #19152, #19153, #19155, #19156, #19158, #19159 — keeper 영역 안 건드림 → CI `Build and Test` SKIPPED gate 통과.
- 본인 PR #19151 (RFC-0145 narrow) 머지 시점부터 새 PR base 가 broken main → `dune build lib/` 검증 시도하면 surface.

본 PR 의 patch 는 1 줄 (line 604):

```diff
- (Agent_sdk.Error.Api
-    (Agent_sdk.Error.Timeout
+ (Agent_sdk.Error.Api
+    (Timeout
        { message = ... }))
```

## 왜 prefix 변경?

`Timeout` 는 `Retry.api_error` variant (위치: `/Users/dancer/.opam/.../agent_sdk/llm_provider/retry.mli:43`).  `Agent_sdk.Error` 모듈에는 `type api_error = Retry.api_error` type alias 만 존재 — constructor 직접 export 안 됨.

OCaml constructor resolution: outer constructor `Agent_sdk.Error.Api : api_error -> sdk_error` 의 *payload type* (`api_error`) 가 inner constructor 의 namespace 를 *pin*. 따라서 `Timeout {...}` 만으로 컴파일러가 `Retry.api_error.Timeout` 로 resolve.

인라인 주석에 이 reasoning 명시 — 향후 reader 가 prefix 변경 시 같은 함정 회피.

## 영향

- `dune build lib/` PASS (main broken 해소)
- 동작 무변경 — constructor lookup 만 type-correct 화

## ⚠️ Silent breakage 시간선 분석 (docs/audit retrospective §2.5 패턴)

같은 패턴 두 번째 — PR #19099 (Magic Number 시리즈) 의 `dated_jsonl/dune` dep 누락 → 7 시간 silent + PR #19109 hotfix. 이번엔 **PR #19145 → main HEAD 동안 ~10 PR 머지** silent. CI gate `Detect Changed Surfaces` 의 *blind spot* 이 반복 surface 됨.

회고 문서 §4 체크리스트 보강 candidate:
- [ ] PR push 전 *full `dune build lib/`* 검증 (sub-library 만 검증 부족)
- [ ] CI `Build and Test` SKIPPED 상태 의심 — keeper/server/cdal core 영역 변경 시 manual `dune build` 필수

## Workaround Signature Gate

WORKAROUND-WAIVED: Production-blocking main breakage hotfix. 시그니처 3종 비해당:

- ❌ Counter-as-Fix
- ❌ String/substring 분류기
- ❌ N-of-M 패치 — 단일 surgical 1 line

## Related

- PR #19145 — RFC-0197 per-candidate watchdog (breakage 도입)
- PR #19099 / #19109 — 동일한 silent main breakage 패턴 (Magic Number 시리즈)
- docs/audit/2026-05-27-magic-number-time-literal-series-retrospective.md §2.5

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by jeong-sik** [comment]
## Self-review (Best Programmer 기준)

**목표**: main `dune build lib/` 복구 (PR #19145 머지 후 `Unbound constructor Agent_sdk.Error.Timeout` 차단).

**변경**: `lib/keeper/keeper_turn_driver_try_cascade.ml:604` 1줄 (outer prefix drop) + 주석 6줄.  diff = `+7/-1`.

**로컬 검증**:
- worktree base `b67f6d82a` (origin/main)
- `dune build lib/ --root .` exit 0 — full library tree green
- 동작 무변경: OCaml constructor resolution 이 outer constructor (`Agent_sdk.Error.Api`) 의 payload type (`api_error` = `Retry.api_error` alias) 으로 inner constructor `Timeout` namespace 를 pin

**미검증**: 전체 test suite — build green 이 *prerequisite* 라 의도적으로 미실행. 별도 검증은 main green 복구 후 normal flow.

**위험**: 0
- 의미 변경 없음
- constructor lookup 만 type-correct 화
- backward-compat: 기존 caller 는 `Agent_sdk.Error.Api (Timeout {...})` 그대로 매치

**CI fail 원인**:
- Draft Auto-Merge Guard — Draft 상태의 정상 invariant, Ready 전환 시 해소
- Godfile size — PR #19145 가 이미 임계 초과한 pre-existing fail. 본 PR 의 7줄 추가는 *원인 아님*. fix-forward 필요 (별도 decomposition PR).

**사용자 권장 액션** (5+ iter 동안 main HEAD broken):
1. **Draft → Ready** 전환 (Draft Auto-Merge Guard fail 해소)
2. **Admin override / squash merge** — Godfile size 는 pre-existing 이라 본 hotfix 영역 밖
3. main green 복구 → 본 PR + 다른 OPEN PR (#19160 / #19166 / #19169 등) base 정상화

Production-blocking 시점: PR #19145 (RFC-0197) 머지 후 5+ iter. `keeper_turn_driver_try_cascade` 의 watchdog timeout path 가 *compile 자체 불가* — 실제 production keeper turn 의 per-candidate watchdog 가 fired 면 build fail로 fallback 안 됨.

🤖 Posted as part of `/loop` iter 73 — automated self-review per CLAUDE.md PR workflow.
