### PR TITLE
refactor(runtime): use Result syntax in lib/runtime/runtime.ml

### PR DESCRIPTION
**Pull request by jeong-sik**
Phase 2 result-usage modernization for lib/runtime/runtime.ml. Replaces nested match pyramids with flat Result.Syntax pipelines, uses Result.map_error for error wrapping, and extracts a small local load_file_result helper. No public signatures changed.

# ci:skip-test-coverage

### CODE REVIEW

**Comment by jeong-sik** [comment]
[적대 리뷰 · head 0f8aee96910f · Result syntax 시리즈]

## Result syntax 평탄화 + load_file_result SSOT 추출 — semantics 보존, 좋습니다

runtime.ml의 4중 중첩 match(default → find → validate_keeper → validate_librarian)를 `let*` 직렬로 평탄화했습니다. Result syntax 시리즈지만 부가 개선이 있습니다:

1. **`load_file_result` 추출(SSOT)**: 이전에 `try Ok (Fs_compat.load_file path) with ...` 패턴이 `load_config_text`와 `set_runtime_id_for_keeper` 2곳에 중복됐는데, 단일 함수로 빼서 재사용합니다. 중복 코드는 같은 버그를 두 번 갖는다는 점에서 이 추출은 단순 미용이 아니라 회귀 예방입니다.

2. **`Eio.Cancel.Cancelled` re-raise 정확**: `load_file_result`가 `Eio.Cancel.Cancelled`는 re-raise하고 나머지 exn만 Error로 변환합니다. 비동기 취소 예외는 Fun.protect/try로 보호하면 안 된다는 Eio 계약을 정확히 준수합니다.

3. **atomicity + 에러 메시지 보존**: `save_config_text`/`set_runtime_id_for_keeper`의 순서(validate → save_atomic → init_default reload)와 "runtime config saved but reload failed: " 메시지가 이전과 동일합니다. save는 됐는데 reload가 실패한 partial 상태를 동일하게 보고합니다.

`Option.to_result ~none:"..."`로 None/Some match를 표준 라이브러리로 대체한 것도 깔끔합니다. semantics 변화 없이 중첩만 줄였고, net -29줄입니다. 기준에 부합합니다.

**Comment by jeong-sik** [comment]
### `Meta Guards` red는 empty 'skip coverage' 커밋 — #21582와 동일 패턴

이 PR의 빈 커밋 `0f8aee96` (`ci: skip coverage for runtime refactor`)이 `Meta Guards / Run PR hygiene guards`의 **빈-커밋 reject**(`scripts/check-pr-hygiene.sh`, 예외 없음)를 칩니다. #21582에서 같은 패턴을 grounded로 분석했습니다([설명](https://github.com/jeong-sik/masc/pull/21582#issuecomment-4750773701)).

요지: coverage skip 마커 `# ci:skip-test-coverage`는 `test-coverage-check.yml`이 **`$PR_BODY`에서** 읽으므로 PR body에만 있으면 충분 — 마커를 나르는 빈 sync commit은 redundant이고 오히려 hygiene guard를 칩니다. **fix: `0f8aee96` drop** (body 마커는 유지) → Meta Guards green.

캠페인 차원 메모: mechanical Result refactor가 line-count coverage 게이트를 흔들 때마다 빈 skip-커밋을 푸시하면 매 PR이 hygiene guard에 걸립니다. body 마커만 쓰거나, 근본적으로 coverage 게이트를 diff-aware(신규 라인만)로 바꾸는 게 반복을 끊습니다.

(Result refactor 로직 자체는 별개 — runtime.ml의 `init_default` 등은 head에서 일관. 근거: `0f8aee96` 빈 커밋 확인 + #21582 분석.)

**Comment by jeong-sik** [comment]
Adversarial CI blocker: Meta Guards fail because the branch contains an empty ci: skip coverage commit. That makes the PR fail hygiene independently of the runtime.ml refactor. Please squash/remove the empty commit or use the accepted skip mechanism so the guard can evaluate the real change.

**Comment by jeong-sik** [comment]
Addressed the Meta Guards PR hygiene failure.

What changed:
- removed the empty `ci: skip coverage for runtime refactor` commit from branch history via `git rebase --no-keep-empty origin/main`
- kept the existing `# ci:skip-test-coverage` marker in the PR body
- current head contains only the actual runtime Result-syntax refactor commit

Re-ran locally after rebase:
- `ocamlformat --check lib/runtime/runtime.ml`
- `scripts/ci/check-determinism-contract.sh --base origin/main --head HEAD`
- `git diff --check origin/main...HEAD`

Remaining Build/Health failures are the shared `Runtime.init_default` blocker, addressed separately by #21601.

**Comment by jeong-sik** [comment]
Current CI red is the shared Runtime module compile blocker, not this PR-specific behavior.

Observed in the failing Health logs:
- `test/test_keeper_effective_meta_overlay.ml` fails at `module Runtime = Masc.Runtime`
- `Error: Unbound module Masc.Runtime`

The canonical fix is #21601 (`fix(keeper): restore effective meta build and snapshot sync`), which already has Health passing and is waiting on the remaining long-running checks. No additional code change is needed in this PR unless it still fails after #21601 lands/rebases into the branch.

**Comment by jeong-sik** [comment]
Resolved the origin/main rebase conflict in `lib/runtime/runtime.ml`.

Resolution kept the current main-side behavior and re-expressed it in Result syntax:
- preserved `[runtime].cross_verifier` validation and cache refresh
- preserved runtime model capability gate validation
- fixed the stale 4-tuple annotation in `validate_runtime_config_text` to the current 5-tuple shape
- added `test_save_config_text_refreshes_cross_verifier_runtime` to cover the save/validate/reload path and cross_verifier cache update

Local verification on head 1adec08c74cdb66c33d209e7c04159156687ad42:
- `ocamlformat --check lib/runtime/runtime.ml test/test_runtime_config_validity.ml`: pass
- anchored conflict-marker scan: clean
- `git diff --check origin/main..HEAD`: pass
- `python3 scripts/check_test_coverage.py`: pass

Per owner instruction, I did not run Dune build/test locally.

**Comment by jeong-sik** [comment]
Closing: Obsolete or resolved in modern MASC v2 / OAS v0.220.3 architecture.
