### PR TITLE
fix(keeper): retain pause outside Resume_owner

### PR DESCRIPTION
**Pull request by jeong-sik**
## Summary

- make ordinary `masc_keeper_up` reconfiguration preserve `paused` and its typed latch
- keep pause clearing exclusive to the existing Dead-tombstone revival transaction or typed `Resume_owner`
- reject dashboard `boot` with HTTP 409 when durable or live registry truth says the owner is ordinarily paused
- remove boot-time best-effort unpause and its stale resume-specific metric phases
- retire the payload-free `Keeper_directive.Resume` variant and reject legacy gRPC `"resume"`, because that wire format cannot carry generation or operation-ID fences
- preserve Dead-tombstone boot/revival as a separate explicit lifecycle authority

## Stack and scope

Base: `codex/paused-work-resume-surface-20260720` (draft PR #25352).

Together with the base, this removes the known unreceipted resume aliases: dashboard resume, wakeup, keeper_up, dashboard boot, and legacy gRPC raw resume. It does not implement `Transfer_owner`, `Settle_from_source_terminal`, paused-retained fleet metrics, or the 10-Keeper 8-hour acceptance run.

## Validation

- `ocamlc -stop-after parsing` for every changed implementation/interface/test
- `ocamlformat --check` for every changed OCaml file
- `git diff --check`
- `bash scripts/lint/masc-domain-boundary-ratchet.sh --fail` — 0 new violations
- static scan: no `Keeper_directive.Resume`, `wakeup_resume`, boot-resume helper, or retired boot-resume metric labels remain

Local Dune build/tests were intentionally not run; the operator is running builds separately and PR CI remains the build authority.

### CODE REVIEW

**Comment by jeong-sik** [comment]
확인 커밋: `3d4ef6d5d2`. ordinary `masc_keeper_up` reconfiguration이 `paused` + typed latch 보존. pause clearing은 Dead-tombstone revival 또는 typed `Resume_owner`에만 exclusive. dashboard `boot` reject.

**방향 건강 (pause 보존 + exclusive clearing)**: 노 silent clear. **approve 성향**.
