### PR TITLE
fix(test): use supported absolute path check

### PR DESCRIPTION
**Pull request by jeong-sik**
## Summary
- replace the unsupported OCaml stdlib call Filename.is_absolute with the repo-standard not (Filename.is_relative ...) check
- unblocks Health target test/test_rfc_0086_keeper_namespace_invariant.ml on OCaml 5.4.1

## Evidence
- CI Health failure from #22316: test/test_rfc_0086_keeper_namespace_invariant.ml line 191, Error: Unbound value Filename.is_absolute
- Local: git diff --check (pass)
- Local targeted dune test was attempted, but scripts/dune-local.sh refused because external bare dune processes were running outside the repo lock.

### CODE REVIEW

**Comment by jeong-sik** [comment]
Self-review on `02b3a0d398`: no code changes needed.

Checked the target issue from #22316 CI:
- OCaml 5.4.1 does not expose `Filename.is_absolute`; the replacement uses the supported stdlib predicate `Filename.is_relative` and keeps the same test assertion as `not (Filename.is_relative resolved)`.
- Scope is correctly limited to `test/test_rfc_0086_keeper_namespace_invariant.ml`.

Local validation, no local Dune build:
- `ocamlformat --check test/test_rfc_0086_keeper_namespace_invariant.ml`
- `git diff --check origin/main...HEAD`
- OCaml 5.4.1 REPL confirmed `Filename.is_relative : string -> bool`

Current PR state at review time: draft, mergeable, review threads empty; GitHub checks are still queued/pending.
