### ISSUE TITLE
bug(build): main broken after #3639/#3640 — Tool_schema_dsl unbound, Mod_hat missing

### ISSUE THREAD

**Issue by jeong-sik** [jeong-sik/masc-mcp#3666]
## 증상

main (a82bf4022) 빌드 실패:

```
Error: Unbound module Tool_schema_dsl
Error: This variant expression is expected to have type module_tag
       There is no constructor Mod_hat within type module_tag
Error: Syntax error (tool_command_plane_support.ml:306)
```

## 추정 원인

- #3639 (`[codex] refactor #3593 monolith decomposition batch 1`)
- #3640 (`refactor(tools): remove 24 unused tools from MCP surface`)

이 두 PR이 서로 의존하거나, 하나가 다른 하나의 전제를 깨뜨린 것으로 보임.

## 재현

```bash
cd ~/me/workspace/yousleepwhen/masc-mcp
git checkout main  # a82bf4022
opam exec -- dune build
```

직전 커밋 `9cdee76c4` (#3637)은 빌드 성공.

## 영향

MASC 서버 재시작 불가. 이전 빌드로 실행 중인 서버는 동작하지만 새 기능/fix 반영 불가.

**Comment by jeong-sik** [comment]
Fixed in #3661 (fbc12d90f). Main builds again.
