### PR TITLE
fix(test): use repo mapping module in policy source test

### PR DESCRIPTION
**Pull request by jeong-sik**
## Summary

Fix the post-merge Health compile failure from #23571.

`test/test_policy_source_of_status.ml` links `Keeper_repo_mapping` as a direct test dependency, matching existing tests such as `test_playground_repo_readiness.ml`. The merged test still referenced `Masc.Keeper_repo_mapping`, which fails with `Unbound module Masc.Keeper_repo_mapping` in Health job `85649534235`.

## Verification

- `ocamlformat --check test/test_policy_source_of_status.ml`
- `git diff --check`
- `python3 scripts/check_test_coverage.py`
- `rg -n "Masc\\.Keeper_repo_mapping" test/test_policy_source_of_status.ml` returned no matches

No local Dune build/test run; CI remains the build authority for the compile failure.

[근거] GitHub Actions Health job `85649534235` on PR #23571, checked 2026-07-07 23:54 KST, confidence High.

### CODE REVIEW

**Comment by jeong-sik** [comment]
Current head `14ed08290d` 기준 follow-up review입니다.

P0: main compile failure fix입니다. #23571 merge commit에 남은 `Masc.Keeper_repo_mapping` reference가 Health job `85649534235`에서 `Unbound module Masc.Keeper_repo_mapping`로 실패했고, 이 PR은 해당 test surface에서 이미 직접 linked되는 `Keeper_repo_mapping` module path로 돌립니다.

P1: source scope는 `test/test_policy_source_of_status.ml` 한 줄입니다. 기존 `Config_dir_resolver` 수정과 같은 library-name boundary이며 production path는 건드리지 않습니다.

P2: local non-Dune checks 통과했습니다.
- `ocamlformat --check test/test_policy_source_of_status.ml`
- `git diff --check`
- `python3 scripts/check_test_coverage.py`
- `rg -n "Masc\\.Keeper_repo_mapping" test/test_policy_source_of_status.ml` no matches

P3/mergeability: draft PR이고 GitHub상 `MERGEABLE`입니다. CI는 방금 queued됐습니다. Health/Build가 이 compile failure를 실제로 닫는 authority이며, Branch Protection Watchdog red가 나오면 기존 repo protection drift와 분리해서 봅니다.

[근거] #23571 Health job `85649534235` failed log; #23581 current head `14ed08290d`; 확인일시 2026-07-07 23:59 KST; 신뢰도 High.

**Comment by jeong-sik** [comment]
P3 source-review pass @ `14ed082`

- 변경 범위는 `test/test_policy_source_of_status.ml`의 모듈 참조 1줄입니다.
- `test/dune`의 해당 test group은 `masc_test_deps`를 링크하고, `test/deps/dune`에서 `masc.repo_manager`를 re-export하므로 `Keeper_repo_mapping.mappings_toml_basename` bare module 접근이 현재 구조와 맞습니다.
- 기존 실패 원인인 `Masc.Keeper_repo_mapping` 경로만 제거했고, 새 path/env 하드코딩, keeper/runtime 동작 변경, silent failure, heuristic/string-match 변경은 없습니다.

CI/build 판정은 로컬 Dune 없이 GitHub Actions가 최종 신호입니다. 현재는 checks pending으로 확인했습니다.
