### PR TITLE
refactor(keeper): hook introspection JSON에서 파생 카운트 제거 (F4/F5 backend)

### PR DESCRIPTION
**Pull request by jeong-sik**
slot 시스템 감사 후속 (PR #21597 backend 짝). F4/F5의 backend 부분.

## 문제 (F4/F5)
`hook_introspection_json`이 payload 데이터의 순수 파생값 5개를 emit하는데 소비처가 0:
- `slot_count` / `active_slot_count` / `inactive_slot_count` / `slot_names` → `slots`에서 계산 가능 (소비처 repo-wide 0건 확인)
- `deny_list_count` → `deny_list`(= List.length)에서 계산 가능

## 변경
- emit assoc에서 위 5개 필드 제거.
- 미사용이 된 key 상수 4개(`key_slot_count`/`key_active_slot_count`/`key_inactive_slot_count`/`key_deny_list_count`) 제거 (`Keeper_hooks_oas_types` .ml + .mli).

## 검증
- `dune build @lib/keeper_hooks_oas_types/check @lib/keeper/check` exit 0
- OCaml introspection 단위 테스트 없음(이 키들을 단언하는 테스트 0건)
- ⚠️ 전체 `@check`는 무관한 base-broken 테스트 `test/test_keeper_effective_meta_overlay.ml`(`Unbound module Masc.Runtime`, #21596 영역)에서만 실패 — 본 변경과 무관.

## 머지 순서 (정정 — 적대 리뷰 반영)
이전 본문의 "order-independent / `?? 0` harmless" 표현은 부정확했음. 정확히는:
- `deny_list_count` 소비처는 **프론트엔드 #21597** 한 곳. #21604가 #21597보다 **먼저 배포되면** 구 프론트가 `asInt(undefined) ?? 0 = 0`으로 "거부 목록 수: 0"을 표시.
- 단 production deny_list는 항상 비어 있어 `deny_list.length`도 0 → **표시값 동일, cosmetic-only window**(데이터 손상/오류 아님).
- **선호: #21597을 먼저(또는 함께) 머지.** 다른 4개 필드(slot_count 등)는 소비처가 전무해 순서 무관.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by jeong-sik** [comment]
Current CI red is the shared Runtime module compile blocker, not this PR-specific behavior.

Observed in the failing Health logs:
- `test/test_keeper_effective_meta_overlay.ml` fails at `module Runtime = Masc.Runtime`
- `Error: Unbound module Masc.Runtime`

The canonical fix is #21601 (`fix(keeper): restore effective meta build and snapshot sync`), which already has Health passing and is waiting on the remaining long-running checks. No additional code change is needed in this PR unless it still fails after #21601 lands/rebases into the branch.

**Review by anyang-keepers — APPROVED** [review]
Derived count cleanup: slot_count/active_slot_count/inactive_slot_count/slot_names/deny_list_count removed, all consumers compute from slots/deny_list directly. CI green. APPROVED.

**Comment by jeong-sik** [comment]
[적대 리뤰 · head ff31fef7f2e0 · 다차원 워크플로우 — HIGH: live UI silent failure]

## HIGH — deny_list_count producer 제거했으나 dashboard consumer가 아직 읽어 live UI가 항상 0 표시

주석(keeper_hooks_oas_introspection.ml:143-146)이 "every consumer computes them from [slots]/[deny_list] directly ... no reader"라고 단언하지만 **거짓**입니다. verify가 sha-pin으로 확인: dashboard consumer가 deny_list_count를 JSON 필드에서 직접 읽고 있었습니다 — `dashboard.ts:2200 asInt(hooks.deny_list_count)`, `core.ts:1485 deny_list_count: number`, `keeper-config-panel.ts:1175 UI "거부 목록 수" ${c.hooks.deny_list_count}`. 이 PR은 producer만 고치고 dashboard reader를 전혀 수정하지 않아(diff에 dashboard 파일 0건), 이제 `asInt(undefined) ?? 0`가 **항상 0**으로 평가됩니다.

이건 silent failure입니다 — 라이브 UI가 "거부 목록 수: 0"을 거짓으로 표시하더라도 에러/로그 없이 정상 렌더링되어, operator가 deny list가 비어 있다고 오인합니다.

## #21597과 한 쌍 — 이 PR 단독은 consumer가 끊김 (N-of-M)

이 PR(producer 마이그레이션)과 #21597(dashboard consumer를 `deny_list.length` 파생으로 변경)이 **짝**입니다. 각각 단독은 반쪽:
- 이 PR만 머지되면 → dashboard가 끊겨 live UI 거짓 0.
- #21597만 머지되면 → 백엔드가 여전히 emit하는데 dashboard가 무시(#21597 verified low).

두 PR이 같은 deny_list_count 마이그레이션을 producer/consumer로 나눈 N-of-M 구조입니다. 같이 머지되거나 순서를 보장해야 하고, 어느 한쪽이 먼저 main에 가면 임시로 live가 끊깁니다.

## confirmed — mli documented contract 위반 + 테스트 fixture가 회귀 안 잡음

- `.mli` docstring(mli:1-3)이 "without changing the dashboard JSON contract"를 계약으로 선언하는데, 이 PR이 contract에서 필드를 제거합니다. contract를 바꾸면 docstring도 같이 갱신해야 합니다.
- `dashboard.test.ts:1468 fixture deny_list_count:'1'`, `keeper-config-panel.test.ts:91 deny_list_count:0`가 그대로라 producer에서 필드가 사라져도 테스트가 green으로 통과합니다 — live(필드 부재) 경로를 커버 못 하는 fixture 의존. producer 마이그레이션만 끝내고 consumer 회귀 테스트는 남겨둔 상태.

## praise

OCaml producer 정리 자체는 깨끗합니다 — 제거된 4 key(key_slot_count/active/inactive/deny_list_count)에 대해 head 전체에서 남은 참조가 0건, mli/ml 동시 삭제로 SSOT 위반 없이 constant도 같이 제거. slot_count/active/inactive 계열은 dashboard가 실제로 slots에서 직접 계산하고 있었으므로 주석이 사실이었습니다(오직 deny_list_count만 consumer가 있었습니다). 설계 방향(derived state 제거)은 올바르고, 실행이 consumer 동기화 누락으로 끊겼을 뿐입니다. **#21597과 함께 머지되면 완결**.
