### ISSUE TITLE
Build break on main after tool-surface decomposition

### ISSUE THREAD

**Issue by jeong-sik** [jeong-sik/masc-mcp#3663]
## Summary

`origin/main` after the recent tool-surface/lib decomposition work does not pass a focused local build.

## Symptoms

Running a focused build after merging `origin/main` into another branch fails with:

- `Error: Unbound module Tool_schema_dsl`
- `Error: This variant expression is expected to have type module_tag ... There is no constructor Mod_hat`
- `Error: Syntax error` in `lib/tool_command_plane_support.ml`

## Reproduction

From a checkout containing current `origin/main`:

```bash
dune build --root . test/test_tool_auth_coverage.exe test/test_tool_misc_coverage.exe test/test_ci_hardening_source.exe
```

## Observed files

- `lib/tool_command_plane_support.ml`
- `lib/tool_tag_init.ml`
- `lib/tool_schema_dsl.ml`

## Suspected cause

The tool-surface / module decomposition on `main` appears to have landed with at least one broken reference and one malformed file tail.

## Tried

- reproduced the same file contents directly from `origin/main` via `git show origin/main:<path>`
- confirmed the failures are not introduced by the `codex-3652-fail-closed-auth` auth hardening changes
