### PR TITLE
test(dashboard): align IDE context label ellipsis

### LINKED ISSUE #16900: Dashboard CI fails on IDE context lens diagnostic label ellipsis drift
## Symptom
Latest main CI run 26139033404 has Dashboard job 76886466629 failing in `dashboard/src/components/ide/ide-context-lens.test.ts`.

Failure:
- test: `IdeContextLens > links LSP diagnostics into file line anchors`
- expected route link label: `This expression has type string but an int wa...`
- received route link label: `This expression has type string but an int was …`

## Repro
GitHub Actions Dashboard job on main `a8ebbeb28b`: https://github.com/jeong-sik/masc-mcp/actions/runs/26139033404/job/76886466629

## Suspected cause
The production label clipping/normalization now preserves more text and uses Unicode ellipsis, while the test fixture still expects the older ASCII truncation.

## Tried
Confirmed this is separate from the #16879 OCaml build blocker: Build and Test / Lint / Health fail on `dashboard_eval_feed` and `keeper_shell_bash_typed_input`, but Dashboard has this additional TS test assertion failure.

### PR DESCRIPTION
**Pull request by jeong-sik**
## Summary
- align the IDE context lens diagnostic route-label expectation with the shared dashboard `truncate()` contract
- close the latest main Dashboard CI failure where the production label uses Unicode ellipsis

Fixes #16900

## Evidence
- `pnpm install --frozen-lockfile --offline`
- `pnpm vitest run --config vitest.config.ts src/components/ide/ide-context-lens.test.ts --no-file-parallelism --maxWorkers=1`
- `pnpm eslint src/components/ide/ide-context-lens.test.ts`
- `pnpm tsc --noEmit --pretty`
- `git diff --check`

## CI context
Latest main Dashboard job `76886466629` in run `26139033404` failed because `ide-context-lens.test.ts` expected ASCII `...`, while the shared truncate helper emits `…`.

### CODE REVIEW

**Comment by jeong-sik** [comment]
Dependency note from live CI triage:

This PR is the dashboard-only fix for #16900 and local proof is green:
- `pnpm install --frozen-lockfile --offline`
- `pnpm vitest run --config vitest.config.ts src/components/ide/ide-context-lens.test.ts --no-file-parallelism --maxWorkers=1`
- `pnpm eslint src/components/ide/ide-context-lens.test.ts`
- `pnpm tsc --noEmit --pretty`
- `git diff --check`

The current `Lint` failure on run `26142094953` is inherited from broken base main `a8ebbeb28b`, not from this dashboard test diff. The failing OCaml blockers are the same latest-main issues carried by #16879:
- `lib/dashboard_eval_feed/dashboard_eval_feed.ml`: `Error: Unbound module Eio`
- `lib/keeper/keeper_shell_bash_typed_input.mli`: `Error: Unbound type constructor Keeper_tool_bash_input.t`

Operationally, keep this draft dependent on #16879 landing, or rebase after main includes #16879. Stacking this dashboard-only PR on #16879 would make CI green sooner but would duplicate the main-build hotfix diff in this PR, so I am leaving it narrow for now.

**Comment by jeong-sik** [comment]
Follow-up CI cleanup:

Removed the empty `ci: trigger recheck` commit from this branch with `--force-with-lease`; PR head is back to the real dashboard fix commit `d80cb6098b`.

Latest run `26144265767` confirms the branch hygiene issue is fixed:
- `Meta Guards` passed at `2026-05-20T05:56:21Z`
- `Dashboard` passed at `2026-05-20T06:03:19Z`

The remaining `Lint` failure is still inherited from broken base main, not from this dashboard diff:
- `lib/dashboard_eval_feed/dashboard_eval_feed.ml`: `Error: Unbound module Eio`
- `lib/keeper/keeper_shell_bash_typed_input.mli`: `Error: Unbound type constructor Keeper_tool_bash_input.t`

Those are fixed by #16879, whose CI is now green but still draft/policy-blocked. Keep this PR narrow and dependent until #16879 lands, then rebase/re-run.

**Comment by jeong-sik** [comment]
Post-rebase status 2026-05-20 15:20 KST: #16902 is rebased onto recovered main 9a8590f9819abc9ecbfc7d85c73569f6652e9ebb at head 536cc62b751b1e1e96eeb5e4f2126a2d25da979c. Local proof passed before push: pnpm install --frozen-lockfile --offline, targeted vitest for ide-context-lens.test.ts, eslint on the touched test, tsc --noEmit, and git diff --check. GitHub CI run 26144830542 is green: PR Sync Check, PR Live Gate, Detect Changed Surfaces, Keeper Cwd Leak Gate, Lint, Meta Guards, Dashboard, and CI Gate all passed; Build and Test, Health, OCaml Structure Ratchet, and TLA+ were skipped by dashboard-only changed-surface scope. The only red check is Draft Auto-Merge Guard, expected because this PR is intentionally still draft. Not marking ready or merging without human approval.

**Comment by jeong-sik** [comment]
Post-latest-main rebase status 2026-05-20 15:36 KST: origin/main advanced again to d31055cd155f3fb776c57b03c0efae912237671a via #16860/#16861/#16863 after #16879 merged, so #16902 was rebased again and force-pushed to head 9730aa2882c8b0b887968eece41ee376d5d0419d. Diff remains one line in dashboard/src/components/ide/ide-context-lens.test.ts. Local proof after this rebase passed: pnpm install --frozen-lockfile --offline, targeted vitest for ide-context-lens.test.ts (24 tests), eslint on the touched test, tsc --noEmit --pretty, and git diff --check. GitHub CI run 26145421836 is green: PR Sync Check, PR Live Gate, Detect Changed Surfaces, Keeper Cwd Leak Gate, Lint, Meta Guards, Dashboard, and CI Gate all passed; Build and Test, Health, OCaml Structure Ratchet, and TLA+ were skipped by dashboard-only changed-surface scope. The only red check remains Draft Auto-Merge Guard, expected because the PR is intentionally still draft. Not marking ready or merging without human approval.
