### PR TITLE
fix(build): repair main after #3640 merge

### LINKED ISSUE #3663: Build break on main after tool-surface decomposition
## Summary

`origin/main` after the recent tool-surface/lib decomposition work does not pass a focused local build.

## Symptoms

Running a focused build after merging `origin/main` into another branch fails with:

- `Error: Unbound module Tool_schema_dsl`
- `Error: This variant expression is expected to have type module_tag ... There is no constructor Mod_hat`
- `Error: Syntax error` in `lib/tool_command_plane_support.ml`

## Reproduction

From a checkout containing current `origin/main`:

```bash
dune build --root . test/test_tool_auth_coverage.exe test/test_tool_misc_coverage.exe test/test_ci_hardening_source.exe
```

## Observed files

- `lib/tool_command_plane_support.ml`
- `lib/tool_tag_init.ml`
- `lib/tool_schema_dsl.ml`

## Suspected cause

The tool-surface / module decomposition on `main` appears to have landed with at least one broken reference and one malformed file tail.

## Tried

- reproduced the same file contents directly from `origin/main` via `git show origin/main:<path>`
- confirmed the failures are not introduced by the `codex-3652-fail-closed-auth` auth hardening changes

### PR DESCRIPTION
**Pull request by jeong-sik**
## Summary

- register `tool_schema_dsl` in `lib/dune` so `tool_command_plane_support.ml` builds again after `#3640`
- remove the stray rebase artifact (`]`) left in `tool_command_plane_support.ml`
- drop the stale `Mod_hat` registration that no longer exists on the MCP surface
- align `masc-mcp` with the current OAS swarm record by adding the new `agent_entry.extensions` field during team-session projection
- bump the `agent_sdk` floor/pin to `0.93.2` and `oas@7fe0229` so CI installs the same API shape this branch now uses

## Product impact

- restores `main` to a buildable state after the `#3640` squash merge
- keeps the MASC team-session bridge compatible with the current OAS `Swarm_types.agent_entry` record shape
- removes the local-vs-CI dependency skew that still pinned `agent_sdk` below the required API surface

## Evidence

Root cause:

- `#3640` landed while CI was still pending and left three source-level build breaks on `main`
- after patching those, a fourth compile break surfaced because OAS recently added the required `agent_entry.extensions` field and `team_session_oas_bridge.ml` still constructed the older record shape
- CI was still pinning `agent_sdk` to an older OAS SHA, so the branch needed the OAS floor/pin ratcheted alongside the source fix

Validation:

- `dune build --root .`
- `scripts/check-oas-pin.sh`

## Review evidence

- GLM-5 cross-model review evidence recorded in PR comments
- Result: no high/critical findings blocking merge

## Linked issue

- Closes #3663
- Relates #3640

### CODE REVIEW

**Comment by jeong-sik** [comment]
Cross-model review evidence

- Model: `GLM-5` via `sb glm-text --no-thinking`
- Timestamp: `2026-03-29 19:00:40 KST`
- Scope: PR head `4906a43d6`
- Result: no high/critical findings

**Comment by jeong-sik** [comment]
Cross-model review evidence

- Model: `GLM-5` via `sb glm-text --no-thinking`
- Timestamp: `2026-03-29 19:19:52 KST`
- Scope: PR head `31298c786`
- Result: no high/critical findings
