### ISSUE TITLE
fix(build): test_eval_feed references missing Masc_mcp.Safe_ops on main

### ISSUE THREAD

**Issue by jeong-sik** [jeong-sik/masc-mcp#6819]
## Symptom

Current `main` still fails `Build and Test` after #6809 because `test/test_eval_feed.ml` references `Masc_mcp.Safe_ops`, which is not exposed.

```
File "test/test_eval_feed.ml", line 278, characters 8-25
Error: Unbound module Masc_mcp.Safe_ops
```

## Repro

- CI run `24325667159`, job `71020378636`
- local repro expected via `opam exec -- dune build --root . test/test_eval_feed.exe`

## Suspected cause

A test helper path drifted after module cleanup or export changes. The test still references the old `Masc_mcp.Safe_ops` path instead of the current helper module/path.

## Impact

Blocks current `main` and any PR rebased on it because `Build and Test` stops at compile time.

**Comment by jeong-sik** [comment]
Safe_ops는 masc_core sub-library로 이동 완료. test_eval_feed는 unqualified Safe_ops 참조 사용 중이며 masc_test_deps의 re_export를 통해 정상 접근. dune build test/test_eval_feed.exe 성공 확인.
