### PR TITLE
refactor: Jane Street Phase 6 (Monadic Error Handling & ppx_let)

### PR DESCRIPTION
**Pull request by jeong-sik**
Phase 6 of Jane Street refactoring:
- Removed legacy permissive fallback from `agent_status_of_string`
- Added `ppx_let` for monadic let%bind syntax support across the codebase

### CODE REVIEW

**Comment by jeong-sik** [comment]
## CI fail diagnosis (autonomous review)

**Lint job root cause** ([job 73120402551](https://github.com/jeong-sik/masc-mcp/actions/runs/24973324027/job/73120402551)):

```
File "lib/keeper/keeper_types_profile.ml", lines 1207-1283, characters 2-3:
Error: Some record fields are undefined: unknown_toml_keys
```

This is **stale base + record-field-add cascade**:

- This PR's base (`eff11397`) predates #11011 which added the `unknown_toml_keys` field to the keeper profile record (merged 02:05Z).
- `keeper_types_profile.ml:1207-1283` constructs a profile record literal that doesn't include the new field.
- After v0.18.4 (#11015) merged at `ba16813423` with 11 additional commits including #11011, the record contract has changed.

**Suggested fix** (1-line):

1. Rebase this branch on current `origin/main` (`ba16813423`).
2. Add `unknown_toml_keys = prefer overlay.unknown_toml_keys base.unknown_toml_keys;` (or whatever the appropriate prefer/merge semantics are for the Phase 6 monadic error handling) to the record literal at line 1207-1283.

**Pattern reference**: this is the `feedback_jane-street-refactor-sweep-miss` pattern (record-field-add variant of `feedback_variant-add-partial-match-cascade`). Build and Test passed at PR's base SHA but fails after rebase against current main because the record contract widened mid-window.

`Health` and `Dashboard` failures likely cascade from the same underlying compile error (downstream consumers of the same profile type).

(Posted by /loop autonomous PR maintenance. Diagnostic only — leaving fix to autocoder iteration so the Phase 6 monadic semantics aren't bypassed.)

**Comment by jeong-sik** [comment]
Rebased on `origin/main` (now base `9954718cf5`, head `c0918e1840`). The `unknown_toml_keys` record-field cascade resolved automatically because #11011's field addition arrived in the rebased main commits (visible at `lib/keeper/keeper_types_profile.ml:1283-1284`). CI re-running.

(Posted by /loop autonomous PR maintenance after autocoder ~50min unresponsive — purely mechanical rebase, no semantic change to Phase 6 monadic refactor.)
