### PR TITLE
[RFC-0264 P2] Memory OS recall injection ledger

### PR DESCRIPTION
**Pull request by jeong-sik**
## 목적

RFC-0264 P2: **recall injection ledger** 구현. 매 turn recall이 프롬프트에 넣은 fact/episode 키를 `trace_id`/`turn`으로 기록 → P3 outcome eval이 `execution_receipt`(trace↔task) + forge(PR/CI merge state)와 조인할 **join key**. "recall이 무엇을 보여줬나 ↔ 그 trace가 어떤 outcome으로 끝났나"를 잇는다.

## 변경

- **신규 `Keeper_recall_injection_ledger`** — `<masc_root>/recall_injections/YYYY-MM/DD.jsonl` day-split. best-effort(write 실패는 로그, turn 중단 안 함), cost-ledger append 패턴 미러.
- `render_context_exn` → record `{block; injected_fact_keys; injected_episode_keys; n_facts_in_store}`. 키는 shared-store dedup용 `private_keys`를 재활용 → **hot-path 추가비용 0**.
- `render_context`는 `string` 시그니처 유지(`.block`) → **외부 caller 무변경**. `render_if_enabled`에 `~trace_id ~turn ~masc_root` 추가, ledger append.
- 단일 호출처(`keeper_run_tools_hooks`) 배선.
- `to_json` round-trip + 필드 단위테스트.

## 검증

- 로컬 `dune build --root .` **green** (worktree 전체 빌드 exit 0).
- 로컬 test **9/9 PASS** (round-trip + 필드 shape + empty 배열).
- CI가 전체 빌드/테스트 재검증.

## 안전

append-only, hot-path read 없음 → **recall 동작 불변**. render_context_exn 시그니처 변경은 내부(mli 미노출), 외부 API(render_context) 호환.

## 워크어라운드 self-check

ledger는 측정 도구지만 **telemetry-as-fix 아님**: P3 ship-gate(`recall_relevance@merged`/`recall_harm@failed`)로 이어지는 join key이며 단순 카운터가 아니다 (RFC-0264 §3.2/§5). 데이터 모델을 추가해 측정→게이트로 연결한다.

WORKAROUND-WAIVED: P2는 측정 인프라(ledger) 추가일 뿐 코드 워크어라운드 없음. RFC-0264 §5가 telemetry-as-fix 회피를 명시.

## 연관

RFC-0264 (#21579, MERGED) · `execution_receipt`(P-a, trace↔task) · 다음 P3 forge collector. 근거: `project-masc-memory-os-adversarial-audit-2026-06-19`.

Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>

### CODE REVIEW

**Comment by jeong-sik** [comment]
Current CI red is the shared Runtime module compile blocker, not this PR-specific behavior.

Observed in the failing Health logs:
- `test/test_keeper_effective_meta_overlay.ml` fails at `module Runtime = Masc.Runtime`
- `Error: Unbound module Masc.Runtime`

The canonical fix is #21601 (`fix(keeper): restore effective meta build and snapshot sync`), which already has Health passing and is waiting on the remaining long-running checks. No additional code change is needed in this PR unless it still fails after #21601 lands/rebases into the branch.

**Review by anyang-keepers — APPROVED** [review]
Re-review after force-push. Changes verified: recall_injection_ledger.ml/mli, render_context_exn→render_result, Dated_jsonl day-split, write failure non-fatal. CI all green. APPROVED.

**Comment by jeong-sik** [comment]
Updated the stale test call-sites for the new RFC-0264 P2 recall API. `test/test_keeper_memory_os.ml` now passes `~trace_id`, `~turn`, and a temp `~masc_root` through a test helper, so the old partial-application type error in `Recall.render_if_enabled` should be gone on the new head (`4bbd1f23ee`).

Local validation:
- `ocamlformat --check test/test_keeper_memory_os.ml`
- `git diff --check`

Focused Dune target validation was attempted with `scripts/dune-local.sh build test/test_keeper_memory_os.exe`, but the wrapper refused to start because existing bare `dune build` processes were already running on the machine. I did not interrupt those processes.

**Comment by jeong-sik** [comment]
[적대 리뷰 · head 4bbd1f23ee74 · 다차원 워크플로우 — HIGH 해소 확인]

## HIGH 해소 — render_if_enabled 시그니처 test 호출부 갱신으로 컴파일 복구 (고쳤습니다)

다차원 워크플로우가 이전 head(87fbabf3fe8a)에서 HIGH를 확인했습니다: `render_if_enabled`가 `trace_id`/`turn`/`masc_root` 3개 필수 라벨 인자를 추가했는데 `test_keeper_memory_os.ml` 6개 호출부가 구 시그니처 `~keeper_id ~now ()`로 남아 컴파일이 깨진다는 것.

새 head(4bbd1f23ee74)에서 `render_if_enabled_for_test ~keeper_id ~now ~masc_root ()` 헬퍼(test_keeper_memory_os.ml:75-76)를 추가해 6개 test 호출부를 갱신했습니다(2-dot diff가 test 파일만 +30/-12, 실제 수정). `.mli` 필수 라벨이 이제 충족되므로 HIGH를 닫습니다.

## low — ledger append가 예외 전부 warn (silent write 실패)

`keeper_recall_injection_ledger.ml:50-53`의 append가 `try Dated_jsonl.append with | Cancel -> raise | exn -> Log.Keeper.warn`로 모든 예외를 경고로 삼킵니다. 디스크 풀/권한/ENOSPC 등 write 실패가 silent log line이 되는데, ledger가 append-only이자 outcome eval의 유일한 join source이므로 기록 누락은 P3에서 recall_relevance/harm 계산이 빠지는 결과로 이어집니다. cancel만 re-raise하고 나머지는 에러 카운터/Result로 올리면 ledger 누락이 visible해집니다.

## low — injected_episode_keys 포맷 inline (SSOT)

`injected_episode_keys` 키 포맷 `Printf.sprintf "%s:g%d" e.trace_id e.generation`이 recall 핫패스에 inline 정의됐습니다. episode (trace_id, generation) 식별자 SSOT가 한 곳이어야 P3 outcome eval과 바이트 일치하는데, 이 포맷이 recall과 향후 P3 reader 양쪽에 산재할 위험이 있습니다. 별도 함수로 추출 권장.

## praise

`Dated_jsonl` 재사용(`keeper_recall_injection_ledger.ml:39`의 cost-ledger 선행 패턴)이 정확하고, RFC-0264 P2(plumbing→ledger) 순서를 정확히 이행합니다. forge terminal state를 ground truth로 쓰는 §4 determinism 경계도 유지됩니다. HIGH까지 고쳐 P2가 탄탄해졌습니다.

**Review by anyang-keepers — APPROVED** [review]
Corrected re-review based on actual diff (origin/main...origin/feature/rfc-0264-p2-recall-ledger). 8 files, +297/-45. Changes verified: render_if_enabled new params, Dated_jsonl day-split, render_context_exn→render_result, recall_injection_ledger.ml/mli, tests. CI all green. APPROVED.

**Comment by jeong-sik** [comment]
### post-merge 적대 리뷰 — novel MEDIUM (live main 이슈로 기록: #21627)

순차 적대 스윕(refute-by-default verify, head 87fbabf)에서 확인한 novel finding을 main 재확인 후 기록합니다. `.mli:13`은 ledger를 **"Bounded"**라 하지만 `Dated_jsonl.create`(`keeper_recall_injection_ledger.ml:39`)가 `retention_days`/`max_bytes` 없이 호출되고, `server_bootstrap_maintenance.ml:366-378` prune allowlist에 `recall_injections`가 **부재** → recall default-on(턴당·키퍼당 1 write)으로 day-file 무한 누적. 같은 파일 :375 주석이 transition-audit의 동일 누락→82MB 선례를 명시.

머지 완료라 PR 블록 대신 추적 이슈 **#21627**로 기록(근본 해소: retention 인자 + prune 등록, 또는 masc_root day-split 자동 커버 SSOT prune). RFC-0264 P2 본체(per-turn ledger, append-only, hot-path 무영향)는 sound — 이 건은 운영 retention 누락 1건뿐입니다.

(차등 적대 리뷰 2026-06-19, 워크플로 w9m5otuer harvest.)
